name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/keymap_draser.yml"
      - "keymap_drawer.config.yaml"
      - "config/**"

jobs:
  draw:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install keymap-drawer
        run: |
          pipx install keymap-drawer==0.22.0
          pipx inject keymap-drawer "tree-sitter<0.25"
          pipx install west
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Fetch west modules
        run: |
          west init -l config
          west update
      - name: Draw keymaps
        run: |
          keymap parse -c 10 -z config/keyball39.keymap > config/keyball39.yaml
          keymap draw -c keymap_drawer.config.yaml config/keyball39.yaml > keymap-drawer/keyball39.svg
      - name: Commit generated keymaps
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add keymap-drawer/*.svg config/*.yaml
          git diff --cached --quiet || git commit -m "Auto-update keymap drawings"
          git push
