name: Draw ZMK keymaps

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/keymap_drawer.yml"
      - "keymap_drawer.config.yaml"
      - "config/**"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@v0.22.1
    permissions:
      contents: write
    with:
      commit_message: "[Draw] ${{ github.event.head_commit.message }}"
      amend_commit: false
      install_branch: ""
      install_version: "0.22.1"
      keymap_patterns: "config/*.keymap"
      json_path: "config"
      config_path: "keymap_drawer.config.yaml"
      output_folder: "keymap-drawer"
      destination: "both"
